version: '3'
services:
  flask-app:
    image: python:3.10.2
    volumes:
      - ./backend:/app
    ports:
      - "15000:5000"
    working_dir: /app
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
    command: sh -c "pip install --no-cache-dir -r requirements.txt && OPENAI_KEY=$(cat /run/secrets/openai_key) flask run --reload"
    secrets:
      - openai_key
    networks:
      - fullyhacks-network

  web-app:
    image: node:14-alpine
    volumes:
      - ./frontend/my-app:/app
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    networks:
      - fullyhacks-network

networks:
  fullyhacks-network:
    driver: bridge


secrets:
  openai_key:
   file: ./backend/openai_key.txt



